//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorCopy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FloorCopy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy floor.
        /// </summary>
        internal static string CopyFloor {
            get {
                return ResourceManager.GetString("CopyFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new floor openings.
        /// </summary>
        internal static string CreateNewFloorOpenings {
            get {
                return ResourceManager.GetString("CreateNewFloorOpenings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor does not have top face.
        /// </summary>
        internal static string FloorDoesNotHaveTopFace {
            get {
                return ResourceManager.GetString("FloorDoesNotHaveTopFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor top face does not have edges.
        /// </summary>
        internal static string FloorTopFateDoesNotHaveEdges {
            get {
                return ResourceManager.GetString("FloorTopFateDoesNotHaveEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a floor.
        /// </summary>
        internal static string SelectFloor {
            get {
                return ResourceManager.GetString("SelectFloor", resourceCulture);
            }
        }
    }
}
